### ISSUE TITLE
Undefined method for requirejs_include_tag

### ISSUE THREAD

**Issue by neersighted** [jwhitley/requirejs-rails#73]
I'm working on a Rails (3.2.2), and since adding `requirejs-rails` to my project, I've been getting errors like:

```
undefined method `requirejs_include_tag' for #<#<Class:0xcc90390>:0xcef59f0>
```

I can post my `Gemfile` and `requirejs.yml` on request, but this error seems to be a problem in the Gem itself. 

I have tried both `require`ing it in my views, and `include`ing it in my `ApplicationHelper`, to no avail. 

Any help is appreciated.
